### GET all tasks
GET http://localhost:8080/api/tasks

### GET task by id
GET http://localhost:8080/api/tasks/1

### GET task by name
GET http://localhost:8080/api/tasks/name?name=Projekt vorbereiten
Accept: application/json

### GET task by category
GET http://localhost:8080/api/tasks/category?category=Work
Accept: application/json

### GET task by priority
GET http://localhost:8080/api/tasks/priority?priority=High
Accept: application/json

### GET task by complexity
GET http://localhost:8080/api/tasks/complexity?complexity=Medium
Accept: application/json

### GET task by status
GET http://localhost:8080/api/tasks/status?status=OPEN
Accept: application/json

### CREATE a task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "name": "Projektabschluss vorbereiten",
  "created": "2025-09-24",
  "dueDate": "2025-09-30",
  "details": "Abschlussbericht schreiben und finalisieren",
  "category": "Work",
  "priority": "High",
  "complexity": "Medium",
  "status": "OPEN"
}

### DELETE a task
DELETE http://localhost:8080/api/tasks/3

### UPDATE a task
PUT http://localhost:8080/api/tasks
Content-Type: application/json

{
  "id": 2,
  "name": "Dokumentation verfassen",
  "status": "DONE"
}