classDiagram
    class Task {
        -int id
        -String name
        -String details
        -Date created
        -Date dueDate
        -Category category
        -Priority priority
        -Complexity complexity
        -Status status
        -List subtasks
        +addTask()
        +updateTask()
        +deleteTask()
        +completeTask()
    }

    class SubTask {
        -int id
        -String name
        -boolean completed
        -Task task
        +addSubTask()
        +updateSubTask()
        +deleteSubTask()
        +completeSubTask()
    }

    Task *-- SubTask