classDiagram
    class Task {
        -int id
        -String name
        -String details
        -Date created
        -Date dueDate
        -String category
        -String priority
        -String complexity
        -Status status
        -List subtasks
        +addTask()
        +updateTask()
        +deleteTask()
        +completeTask()
    }

    class SubTask {
        -int id
        -String name
        -String details
        -boolean completed
        -Task task
        +addToTask()
        +addSubTask()
        +updateSubTask()
        +deleteSubTask()
        +completeSubTask()
    }

    class Reminder {
        -int id
        -int taskId
        -Date dateToRemind
        -String message
        +addReminder()
        +updateReminder()
        +deleteReminder()
    }

    Task *-- SubTask
    Task *-- Reminder